spring.application.name=teste-Iniflex

# ============== CONFIGURACOES H2 =================

# Console H2: http://localhost:8080/h2-console

spring.datasource.url=jdbc:h2:file:./data/iniflex
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cria e atualiza as tabelas
spring.jpa.hibernate.ddl-auto=update
